steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/kube-slack:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/kube-slack:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/kube-slack'
      - 'kube-slack=gcr.io/$PROJECT_ID/kube-slack:$REVISION_ID'
      - '--namespace'
      - 'kube-system'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=minejs-cluster-1'